---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    container_name: kafka
    depends_on:
      - zookeeper
    networks:
      - kafka-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: hepsiburada/postgres:13.1-case
    ports:
      - "5432:5432"
    environment:
#       - PGDATA=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata2
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kafka-network

  data-producer:
    build: data-producer/.
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - kafka-network
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092

  etl:
    build: etl/.
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - kafka-network
    environment:
      - DATA_DB_URL=jdbc:postgresql://postgres/postgres
      - DATA_DB_USER=postgres
      - DATA_DB_PASSWORD=123456
      - API_DB_URL=jdbc:postgresql://postgres/postgres
      - API_DB_USER=postgres
      - API_DB_PASSWORD=123456
    
  streaming:
    build: streaming/.
    restart: unless-stopped
    depends_on:
      - kafka
      - postgres
    networks:
      - kafka-network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=123456

  api:
    build: api/.
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - kafka-network
    environment:
      - APP_PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=123456

networks:
  kafka-network:
    name: kafka-network


